/*
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
*/

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <stdbool.h>

#include <string.h>

// #define A389
#ifdef A389

/*
char findTheDifference(char* s, char* t) {
	int flag[26] = { 0 }, i;
	char *p = s;
	for (p = s; *p != '\0'; p++)
	{
		flag[*p - 'a']++;
	}
	for (p = t; *p != '\0'; p++)
	{
		flag[*p - 'a']++;
	}
	for (i = 0; i <26; i++)
	{
		if (flag[i] % 2 != 0){
			return i + 'a';
		}
	}
	return 'a'; // ·ÀÖ¹±àÒë³ö´í
}
*/

char findTheDifference(char* s, char* t) {
	char ret = 0;
	while (*s) { ret -= *s; s++; }
	while (*t) { ret += *t; t++; }
	return ret;
}

int main(){
	printf("%c\n", findTheDifference("","a"));
	getchar();
	return 0;
}

#endif